england_regions = [
    "North East", 
    "North West", 
    "Yorkshire and the Humber", 
    "East Midlands", 
    "West Midlands", 
    "East of England", 
    "London", 
    "South East", 
    "South West"
    ]

africa_region = [
    "Algeria", 
    "Angola", 
    "Benin", 
    "Botswana", 
    "Burkina Faso", 
    "Burundi", 
    "Cabo Verde", 
    "Cameroon", 
    "Central African Republic", 
    "Chad", 
    "Comoros", 
    "Congo (Democratic Republic)", 
    "Congo", 
    "Cote d'Ivoire", 
    "Ivory Coast",
    "Djibouti", "Egypt", 
    "Equatorial Guinea", 
    "Eritrea", 
    "Eswatini", 
    "Ethiopia", 
    "Gabon", 
    "The Gambia", 
    "Ghana", 
    "Guinea", 
    "Guinea-Bissau", 
    "Kenya", 
    "Lesotho", 
    "Liberia", 
    "Libya", 
    "Madagascar", 
    "Malawi", 
    "Mali", 
    "Mauritania", 
    "Mauritius", 
    "Morocco", 
    "Mozambique", 
    "Namibia", 
    "Niger", 
    "Nigeria", 
    "R\u00e9union",
    "Rwanda", 
    "Sao Tome and Principe", 
    "Senegal", 
    "Seychelles", 
    "Sierra Leone", 
    "Somalia", 
    "South Africa", 
    "South Sudan", 
    "Sudan", 
    "Tanzania", 
    "Togo", 
    "Tunisia", 
    "Uganda", 
    "Western Sahara",
    "Zambia", 
    "Zimbabwe"
    ]

asia_region = [
    "Afghanistan", 
    "Armenia", 
    "Azerbaijan", 
    "Bahrain", 
    "Bangladesh", 
    "Bhutan", 
    "Brunei", 
    "Burma", 
    "Cambodia", 
    "China", 
    "Cyprus", 
    "East Timor",
    "Georgia",
    "Hong Kong",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Israel",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Lebanon",
    "Macau",
    "Malaysia",
    "Maldives",
    "Mongolia",
    "Myanmar (Burma)",
    "Nepal",
    "North Korea",
    "Oman",
    "Pakistan",
    "Philippines",
    "Qatar",
    "Russia",
    "Saudi Arabia",
    "Singapore",
    "South Korea",
    "Sri Lanka",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Thailand",
    "The Occupied Palestinian Territories",
    "Turkey",
    "Turkmenistan",
    "United Arab Emirates",
    "Uzbekistan",
    "Vietnam",
    "Yemen"
    ]

carribean_region = [
    "Anguilla",
    "Antigua and Barbuda",
    "Aruba",
    "Bahamas",
    "Barbados",
    "Bermuda",
    "British Virgin Islands",
    "Cayman Islands",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Grenada",
    "Guadeloupe",
    "Haiti",
    "Jamaica",
    "Martinique",
    "Montserrat",
    "Netherlands Antilles",
    "Puerto Rico",
    "St Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Trinidad and Tobago",
    "Turks and Caicos Islands",
    "US Virgin Islands"
    ]

central_america_region = [
    "Belize",
    "Costa Rica",
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Mexico",
    "Nicaragua",
    "Panama"
    ]

europe_region = [
    "Albania",
    "Andorra",
    "Austria",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Czech Republic",
    "Czechia",
    "Denmark",
    "Estonia",
    "Faroe Islands",
    "Finland",
    "France",
    "Germany",
    "Gibraltar",
    "Greece",
    "Guernsey",
    "Hungary",
    "Iceland",
    "Isle of Man",
    "Ireland",
    "Italy",
    "Jersey",
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Svalbard",
    "Sweden",
    "Switzerland",
    "Ukraine",
    "United Kingdom",
    "Vatican City"
    ]

north_america_region = [
    "Canada",
    "Greenland",
    "Mexico",
    "Saint Pierre and Miquelon",
    "United States"
    ]

oceania_region = [
    "American Samoa",
    "Australia",
    "Christmas Island",
    "Cocos Islands",
    "Cook Islands",
    "Fiji",
    "French Polynesia",
    "Guam",
    "Kiribati",
    "Marshall Islands",
    "Micronesia",
    "Nauru",
    "New Caledonia",
    "New Zealand",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Palau",
    "Papua New Guinea",
    "Pitcairn Islands",
    "Samoa",
    "Solomon Islands",
    "Tokelau",
    "Tonga",
    "Tuvalu",
    "Vanuatu",
    "Wallis and Futuna"
    ]

south_america_region = [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Ecuador",
    "Falkland Islands",
    "French Guiana",
    "Guyana",
    "Paraguay",
    "Peru",
    "Suriname",
    "Uruguay",
    "Venezuela"
    ]
